name: CI/CD EProject Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # --- B1. Checkout code ---
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- B2. Create .env files ---
      - name: Create .env files
        run: |
          mkdir -p auth product order

          # Auth
          echo "MONGODB_AUTH_URI=mongodb://mongo:27017/auth_db" >> auth/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> auth/.env

          # Product
          echo "MONGODB_PRODUCT_URI=mongodb://mongo:27017/product_db" >> product/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> product/.env
          echo "AUTH_SERVICE_URL=http://auth:4001" >> product/.env
          echo "LOGIN_TEST_USER=${{ secrets.LOGIN_TEST_USER }}" >> product/.env
          echo "LOGIN_TEST_PASSWORD=${{ secrets.LOGIN_TEST_PASSWORD }}" >> product/.env

          # Order
          echo "MONGODB_ORDER_URI=mongodb://mongo:27017/order_db" >> order/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> order/.env
          echo "AUTH_SERVICE_URL=http://auth:4001" >> order/.env
          echo "PRODUCT_SERVICE_URL=http://product:4002" >> order/.env

      # --- B3. Build Docker images ---
      - name: Build Docker images
        run: |
          docker build -t auth-service ./auth
          docker build -t product-service ./product
          docker build -t order-service ./order

      # --- B4. Create Docker network ---
      - name: Create Docker network
        run: docker network create eproject-net || true

      # --- B5. Start MongoDB ---
      - name: Start MongoDB
        run: |
          docker run -d --name mongo --network eproject-net mongo:6
          sleep 10

      # --- B6. Start Auth service ---
      - name: Start Auth service
        run: |
          docker run -d --name auth \
            --network eproject-net \
            --env-file ./auth/.env \
            auth-service
          # Wait until Auth is ready
          for i in {1..20}; do
            if docker exec auth curl -s http://localhost:4001/health; then break; else sleep 3; fi
          done
          echo "Auth service is ready"

      # --- B7. Run Auth tests ---
      - name: Run Auth tests
        run: |
          docker exec auth npm test

      # --- B8. Start Product service ---
      - name: Start Product service
        run: |
          docker run -d --name product \
            --network eproject-net \
            --env-file ./product/.env \
            product-service
          # Wait until Product is ready
          for i in {1..20}; do
            if docker exec product curl -s http://localhost:4002/health; then break; else sleep 3; fi
          done
          echo "Product service is ready"

      # --- B9. Run Product tests ---
      - name: Run Product tests
        run: |
          docker exec product npm test

      # --- Cleanup (optional, cuối workflow) ---
      - name: Cleanup containers and network
        if: always()
        run: |
          docker ps -a
          docker stop $(docker ps -aq) || true
          docker rm $(docker ps -aq) || true
          docker network rm eproject-net || true
