name: CI/CD EProject Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # --- B1. Checkout code ---
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- B2. Create .env files ---
      - name: Create .env files
        run: |
          mkdir -p auth product

          # Auth service .env
          echo "MONGODB_AUTH_URI=mongodb://mongo:27017/auth_db" > auth/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> auth/.env
          echo "LOGIN_TEST_USER=${{ secrets.LOGIN_TEST_USER }}" >> auth/.env
          echo "LOGIN_TEST_PASSWORD=${{ secrets.LOGIN_TEST_PASSWORD }}" >> auth/.env

          # Product service .env
          echo "MONGODB_PRODUCT_URI=mongodb://mongo:27017/product_db" > product/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> product/.env
          echo "AUTH_SERVICE_URL=http://auth:4001" >> product/.env
          echo "LOGIN_TEST_USER=${{ secrets.LOGIN_TEST_USER }}" >> product/.env
          echo "LOGIN_TEST_PASSWORD=${{ secrets.LOGIN_TEST_PASSWORD }}" >> product/.env
          echo "RABBITMQ_HOST=rabbitmq" >> product/.env
          echo "RABBITMQ_PORT=5672" >> product/.env
          echo "RABBITMQ_USER=${{ secrets.RABBITMQ_USER }}" >> product/.env
          echo "RABBITMQ_PASS=${{ secrets.RABBITMQ_PASS }}" >> product/.env

      # --- B3. Build Docker images ---
      - name: Build Docker images
        run: |
          docker build -t auth-service ./auth
          docker build -t product-service ./product

      # --- B4. Create Docker network ---
      - name: Create Docker network
        run: docker network create eproject-net || true

      # --- B5. Start MongoDB ---
      - name: Start MongoDB
        run: |
          docker run -d --name mongo --network eproject-net mongo:6
          # Wait Mongo ready
          for i in {1..20}; do
            if docker exec mongo mongo --eval "db.adminCommand('ping')" &>/dev/null; then break; else sleep 3; fi
          done

      # --- B6. Start RabbitMQ ---
      - name: Start RabbitMQ
        run: |
          docker run -d --name rabbitmq \
            --network eproject-net \
            -e RABBITMQ_DEFAULT_USER=${{ secrets.RABBITMQ_USER }} \
            -e RABBITMQ_DEFAULT_PASS=${{ secrets.RABBITMQ_PASS }} \
            rabbitmq:3-management
          sleep 10

      # --- B7. Start Auth service ---
      - name: Start Auth service
        run: |
          docker run -d --name auth --network eproject-net --env-file ./auth/.env auth-service
          # Wait Auth ready
          for i in {1..20}; do
            if docker exec auth curl -s http://auth:4001/health; then break; else sleep 3; fi
          done
          # Create test user safely
          docker exec auth node -e "
            const AuthService = require('./src/services/authService');
            const authService = new AuthService();
            const username = process.env.LOGIN_TEST_USER;
            const password = process.env.LOGIN_TEST_PASSWORD;

            (async () => {
              let connected = false;
              while (!connected) {
                try {
                  await authService.deleteTestUsers();
                  connected = true;
                } catch (err) {
                  console.log('MongoDB chưa sẵn sàng, đợi 2s...');
                  await new Promise(r => setTimeout(r, 2000));
                }
              }
              await authService.register({ username, password });
              console.log('Test user created via AuthService.register()');
              process.exit();
            })().catch(err => { console.error(err); process.exit(1); });
          "

      # --- B8. Start Product service ---
      - name: Start Product service
        run: |
          docker run -d --name product --network eproject-net --env-file ./product/.env product-service
          for i in {1..20}; do
            if docker exec product curl -s http://product:4002/health; then break; else sleep 3; fi
          done

      # --- B9. Run all tests ---
      - name: Run all tests
        run: |
          docker exec auth npm test
          docker exec product npm test

      # --- B10. Cleanup ---
      - name: Cleanup
        if: always()
        run: |
          docker stop auth product mongo rabbitmq || true
          docker rm auth product mongo rabbitmq || true
          docker network rm eproject-net || true
