name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env files
      run: |
        echo "MONGODB_AUTH_URI=mongodb://mongo:27017/auth_db" >> auth/.env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> auth/.env
        echo "MONGODB_PRODUCT_URI=mongodb://mongo:27017/product_db" >> product/.env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> product/.env
        echo "LOGIN_TEST_USER=${{ secrets.LOGIN_TEST_USER }}" >> product/.env
        echo "LOGIN_TEST_PASSWORD=${{ secrets.LOGIN_TEST_PASSWORD }}" >> product/.env

    - name: Install dependencies
      run: |
        cd auth && npm install
        cd ../product && npm install
        cd ../order && npm install

    - name: Run Auth tests
      run: |
        cd auth
        sleep 15
        npm test

    - name: Run Product tests
      run: |
        cd product
        npm start &
        SERVER_PID=$!
        sleep 15
        npm test
        kill $SERVER_PID

    - name: Run Order tests
      run: |
        cd order
        npm start &
        SERVER_PID=$!
        sleep 15
        npm test
        kill $SERVER_PID
