name: CI/CD EProject Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # --- B1. Lấy code ---
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- B2. Tạo file .env cho từng service ---
      - name: Create .env files
        run: |
          echo "MONGODB_AUTH_URI=mongodb://localhost:27017/auth_db" >> auth/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> auth/.env

          echo "MONGODB_PRODUCT_URI=mongodb://localhost:27017/product_db" >> product/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> product/.env
          echo "AUTH_SERVICE_URL=http://localhost:4001" >> product/.env
          echo "LOGIN_TEST_USER=${{ secrets.LOGIN_TEST_USER }}" >> product/.env
          echo "LOGIN_TEST_PASSWORD=${{ secrets.LOGIN_TEST_PASSWORD }}" >> product/.env

          echo "MONGODB_ORDER_URI=mongodb://localhost:27017/order_db" >> order/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> order/.env
          echo "AUTH_SERVICE_URL=http://localhost:4001" >> order/.env
          echo "PRODUCT_SERVICE_URL=http://localhost:4002" >> order/.env

      # --- B3. Cài dependencies ---
      - name: Install dependencies
        run: |
          cd auth && npm ci && cd ..
          cd product && npm ci && cd ..
          cd order && npm ci && cd ..

      # --- B4. Start MongoDB service ---
      - name: Start MongoDB
        run: |
          docker run -d -p 27017:27017 --name mongo mongo:6
          sleep 10

      # --- B5. Test Auth ---
      - name: Run Auth tests
        run: |
          cd auth
          npm test

      # --- B6. Test Product (cần Auth chạy trước) ---
      - name: Run Product tests
        run: |
          cd auth
          npm start &
          sleep 10
          cd ../product
          npm test

      # --- B7. Test Order (cần Auth + Product chạy trước) ---
      - name: Run Order tests
        run: |
          cd auth
          npm start &
          cd ../product
          npm start &
          sleep 15
          cd ../order
          npm test
