name: CI/CD EProject Microservices (Docker + Test thật)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ----------------------------------------------------------
  # 🧪 B1. TEST TỪNG SERVICE (Docker + MongoDB + RabbitMQ thật)
  # ----------------------------------------------------------
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=10

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
        options: >-
          --health-cmd="rabbitmq-diagnostics -q ping"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=10

    strategy:
      matrix:
        service: [auth, product]
        node-version: [20.x]

    steps:
      # --- Lấy code ---
      - uses: actions/checkout@v4

      # --- Cài Node.js ---
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # --- Tạo Docker network ---
      - name: Create Docker network
        run: docker network create eproject-net || true

      # --- Build service image ---
      - name: Build ${{ matrix.service }} image
        run: docker build -t eproject-${{ matrix.service }} ./${{ matrix.service }}

      # --- Chạy Auth container trước nếu cần ---
      - name: Start Auth container (for Product test)
        if: matrix.service == 'product'
        run: |
          docker run -d --name auth --network eproject-net \
            -e MONGODB_AUTH_URI=mongodb://mongodb:27017/auth_test \
            -e JWT_SECRET=${{ secrets.JWT_SECRET || 'dummysecret' }} \
            -p 3000:3000 \
            eproject-auth
          sleep 15

      # --- Chạy service container để test ---
      - name: Start ${{ matrix.service }} container
        run: |
          ENV_FILE=./${{ matrix.service }}/.env
          mkdir -p ${{ matrix.service }}
          
          if [ "${{ matrix.service }}" = "auth" ]; then
            echo "MONGODB_AUTH_URI=mongodb://mongodb:27017/auth_test" > $ENV_FILE
            echo "JWT_SECRET=${{ secrets.JWT_SECRET || 'dummysecret' }}" >> $ENV_FILE
            echo "PORT=3000" >> $ENV_FILE
          fi
          
          if [ "${{ matrix.service }}" = "product" ]; then
            echo "MONGODB_PRODUCT_URI=mongodb://mongodb:27017/product_test" > $ENV_FILE
            echo "JWT_SECRET=${{ secrets.JWT_SECRET || 'dummysecret' }}" >> $ENV_FILE
            echo "AUTH_SERVICE_URL=http://auth:3000" >> $ENV_FILE
            echo "PORT=3001" >> $ENV_FILE
          fi

          echo "RABBITMQ_URL=amqp://rabbitmq:5672" >> $ENV_FILE

          docker run -d --name ${{ matrix.service }} --network eproject-net \
            --env-file $ENV_FILE \
            -p $([[ "${{ matrix.service }}" = "auth" ]] && echo 3000 || echo 3001):$([[ "${{ matrix.service }}" = "auth" ]] && echo 3000 || echo 3001) \
            eproject-${{ matrix.service }}
          sleep 15

      # --- Chạy test thật ---
      - name: Run tests for ${{ matrix.service }}
        run: docker exec ${{ matrix.service }} npm test --if-present
        env:
          NODE_ENV: test

  # ----------------------------------------------------------
  # 🐳 B2. BUILD + PUSH IMAGE SAU KHI TEST PASS
  # ----------------------------------------------------------
  build_push:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'

    strategy:
      matrix:
        service: [auth, product]

    steps:
      # --- Lấy code ---
      - uses: actions/checkout@v4

      # --- Setup Docker Buildx ---
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- Đăng nhập Docker Hub ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --- Build và Push từng service ---
      - name: Build and Push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/eproject-${{ matrix.service }}:latest
            ${{ secrets.DOCKER_USERNAME }}/eproject-${{ matrix.service }}:${{ github.sha }}

  # ----------------------------------------------------------
  # 🧹 B3. CLEANUP (DỌN CONTAINER SAU CI)
  # ----------------------------------------------------------
  cleanup:
    runs-on: ubuntu-latest
    needs: build_push
    if: always()
    steps:
      - name: Cleanup containers and network
        run: |
          echo "🧹 Cleaning up..."
          docker ps -aq | xargs -r docker stop || true
          docker ps -aq | xargs -r docker rm || true
          docker network prune -f || true

      - name: Finish message
        run: echo "🎯 CI/CD pipeline completed successfully — tested Auth & Product only."
